GET http://localhost:8080/comments
###


POST http://localhost:8080/comments
Content-Type: application/json

{
    "name":"asras"
}
###

GET http://localhost:8080/comments/0
###



DELETE http://localhost:8080/comments/2
###

PATCH  http://localhost:8080/comments/3
Content-Type: application/json

{
    "name":"dunbi",
    "email":"wqee@sadds.com"

}
